;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sentence
        backward-sexp
        beginning-of-buffer
        cljr-raise-sexp
        cljr-slash
        delete-indentation
        electric-newline-and-maybe-indent
        forward-sexp
        kill-region
        kill-sexp
        live-cycle-clj-coll
        paredit-backward
        paredit-backward-barf-sexp
        paredit-close-round
        paredit-close-square
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-newline
        paredit-open-square
        paredit-wrap-round
        subword-left
        subword-right
        upcase-region
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        find-tag-regexp
        ido-find-file
        ido-switch-buffer
        info
        mouse-buffer-menu
        mouse-set-region
        smex
        ))
